<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEUVxYns\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEUVxYns/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEUVxYns.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEUVxYns\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEUVxYns\App_KernelDevDebugContainer([
    'container.build_hash' => 'EUVxYns',
    'container.build_id' => '4b4c85d6',
    'container.build_time' => 1643851979,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEUVxYns');
